BookStore/Controllers/AccontController.cs
using BookStore.Models;
using BookStore.services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Study_3092022.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class AccontController : Controller
    {

 IAccountService IAccountService;
        UserManager<ApplicationUsser> userm;
        RoleManager<IdentityRole> rolemanger;
        SignInManager<ApplicationUsser> signInM;
        public AccontController(IAccountService _IAccountService, UserManager<ApplicationUsser> _userManager, SignInManager<ApplicationUsser> _signInManager, RoleManager<IdentityRole> _rolemanger)
        {

            rolemanger = _rolemanger;
            userm = _userManager;
            signInM = _signInManager;
            IAccountService = _IAccountService;
        }
       
        
 
        public IActionResult Index()
        {
            return View("NewAccount");
        }


        public async Task<IActionResult>  AddNewClint(SignupModel signup)
        
        {
            await IAccountService.AddNewUser(signup);

            return View("NewAccount");
        }

        public IActionResult Login()
        {
            return View("Login");
        }
      
        public async Task<IActionResult> LoginSucces(LoginModel login)
        {

          var result=  await IAccountService.Loginsucces(login);

            if (result.Succeeded == true)
            {
         
               return RedirectToAction("Index", "Book");

            }
            else
             
            {
                ViewData["a"] = "Invalid login";
                return View("NewAccount");

            }


           




        }
        [Authorize]
        public IActionResult NewRole()
            {


                return View("NewRole");
            }
        public async Task<IActionResult> AddRow(RoleModel rolemodel)
        {
            var result = await IAccountService.ADDRole(rolemodel);



            return View("NewRole");
        }
        [Authorize]
        public IActionResult USerList()
        {

            List<ApplicationUsser> li = IAccountService.Userlist();


            return View("USerList", li);
        }

        public async Task<IActionResult> CheackUser(string userid)
        {
            List<UserRole> LI = await IAccountService.RoleList(userid);


            return View("CheackUser", LI);
        }



        public async Task<IActionResult> ubdaterole(List<UserRole> lrole)
        {

            await IAccountService.ubdaterole(lrole);

            List<UserRole> lrolee = await IAccountService.RoleList(lrole[0].userid);

            return View("CheackUser", lrolee);
        }

        public IActionResult signout()
        {

            IAccountService.logout();
            return View("loginpage");

        }


    }
}

BookStore/Controllers/AuthorController.cs
using BookStore.data;
using BookStore.services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class AuthorController : Controller
    {
        IAuthorServices AuthorServices;
        public AuthorController(IAuthorServices _AuthorServices)
        {

            AuthorServices =_AuthorServices;


        }
        public IActionResult Index()
        {
            ViewData["search"] = true;

            List<Author>  li= AuthorServices.InsertAuthor();
        
            return View("NewAuther",li);
        }

        public IActionResult deletAuthor(int dept_Id)
        {
            ViewData["search"] =true
                ;
            AuthorServices.DeletAutor(dept_Id);
            List<Author> li = AuthorServices.InsertAuthor();
               


            return View("NewAuther",li);
        }

        public IActionResult addauthor(Author aut)
        {
            ViewData["search"] = false;

            AuthorServices.addauthor(aut);
            ViewData["isset"] = true;

            return View("AddAuthor");
        }
        public IActionResult open()
        {
            ViewData["search"] = false;

            ViewData["isset"] = true;

            return View("AddAuthor");
        }

        public IActionResult edit(int id)
        {
            ViewData["search"] = false;
            ViewData["isset"] = false;



            return View("AddAuthor", AuthorServices.load(id));
        }


        public IActionResult UbdateBook(Author cat)
        {


            ViewData["search"] = false;
            AuthorServices.Ubdate(cat);
            ViewData["isset"] = true;

            return View("AddAuthor");
        }
    }
}

BookStore/Controllers/CategoryController.cs
using BookStore.data;
using BookStore.services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class CategoryController : Controller
    {

        ICategoryServices CategoryServices;
        public CategoryController(ICategoryServices _CategoryServices)
        {

            CategoryServices = _CategoryServices;


        }


        public IActionResult Index()
        {
            ViewData["search"] = true;

            List<Category> li= CategoryServices.insertcategories();
            return View("NewCategorys",li);
        }


        public IActionResult deletcategory(int dept_Id)
        {
            ViewData["search"] = true;
            CategoryServices.deletcategory(dept_Id);
            List<Category> li = CategoryServices.insertcategories();



            return View("NewCategorys", li);
        }



        public IActionResult open()
        {
            ViewData["search"] = false;
            ViewData["isset"] = true;

            return View("AddCategory");
        }

        public IActionResult AddCategory(Category cat)
        {
            ViewData["search"] = false;
            CategoryServices.addCategore(cat);

            ViewData["isset"] =true;


            return View("AddCategory");
        }


        public IActionResult edit(int id )
        {
            ViewData["search"] = false;

            ViewData["isset"] = false;



            return View("AddCategory", CategoryServices.load(id));
        }


        public IActionResult UbdateBook(Category cat)
        {
            ViewData["search"] = false;
            CategoryServices.Ubdate(cat);
            ViewData["isset"] = true;

            return View("AddCategory");
        }

    }
}

BookStore/Views/Shared/Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUsser> signInM


<!DOCTYPE html>

<html>
<head>

    <style type="text/css">
        body {
            background-color: rgb(210, 210, 210);
        }
    </style>
    @RenderSection("head", false)



    <link href="~/bootstrap/dist/css/bootstrap.css" rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=device-width" />
    <title>Layouts</title>

    <link href="~/bootstrap/dist/css/bootstrap.css" rel="stylesheet" type="text/css">
    <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" type="text/javascript"></script>
    <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" type="text/javascript"></script>
</head>
<body style="background-color: rgb(238, 238, 238); ">

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style=" ">Book</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                 
                    <li><a asp-action="Index" asp-controller="Book">New Book</a></li>
                    <li><a asp-action="openList" asp-controller="Book">List Book</a></li>
                    <li><a asp-action="open" asp-controller="Author">New Author</a></li>
                    <li><a asp-action="Index" asp-controller="Author">List Author</a></li>
                    <li><a asp-action="open" asp-controller="Category">New Category</a></li>
                    <li><a asp-action="Index" asp-controller="Category">List Catigory</a></li>


                </ul>
                @if ((bool)ViewData["search"] == true)
                {
                    <form class="navbar-form navbar-right" method="post">
                        <div class="form-group">
                            <input type="text"  name="searche" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" asp-action="search" asp-controller="Book" class="btn btn-default">Submit</button>
                    </form>
                }
                else
                {  }




            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>


            @RenderSection("Body")








</body>
</html>

BookStore/Views/Shared/Layout2.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUsser> signInM


<!DOCTYPE html>

<html>
<head>

    <style type="text/css">
        body {
            background-color: rgb(210, 210, 210);
        }
    </style>
    @RenderSection("head", false)



    <link href="~/bootstrap/dist/css/bootstrap.css" rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=device-width" />
    <title>Layouts</title>

    <link href="~/bootstrap/dist/css/bootstrap.css" rel="stylesheet" type="text/css">
    <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" type="text/javascript"></script>
    <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" type="text/javascript"></script>
</head>
<body style="background-color: rgb(238, 238, 238); ">

    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <nav class="navbar-inverse">
                    <div class="navbar-brand">
                        HR System
                    </div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-target="#menu1" data-toggle="collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div id="menu1" class="navbar-collapse collapse">
                        @*@if (signInM.IsSignedIn(User))
                        {*@

                            <ul class="nav navbar-nav">
                                <li>
                                    <a asp-action="NewRole" asp-controller="Accont">NEW ROLE</a>
                                </li>
                                <li>
                                    <a asp-action="USerList" asp-controller="Accont">LIST ROLE</a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Accont">DASHBORD</a>
                                </li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li>

                                    <a asp-action="signout"><span class="glyphicon glyphicon-log-in">out</span></a>
                                </li>

                            </ul>
                                @*}
                                else
                                {*@
                                <ul class="nav navbar-nav navbar-right">
                                    <li>


                                        <a asp-action="login" asp-controller="Signup"><span class="glyphicon glyphicon-log-out">LOGIN</span></a>
                                    </li>
                                    <li>

                                        <a asp-action="Index" asp-controller="Signup"><span class="glyphicon glyphicon-log-out">SIGNUP</span></a>
                                    </li>

                                </ul>

                                @*}*@
                        </div>
                </nav>
            </div>
        </div>

        <div>


            @RenderSection("Body")
        </div>





    </div>

</body>
</html>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>